import os, logging, smtplib, ssl, html
from dotenv import load_dotenv
from email.message import EmailMessage
from tenacity import retry, wait_exponential, stop_after_attempt

load_dotenv()

SMTP_HOST = os.getenv("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT = int(os.getenv("SMTP_PORT", "587"))
SMTP_USER = os.getenv("SMTP_USER")
SMTP_PASS = os.getenv("SMTP_PASS")
FROM_EMAIL = os.getenv("FROM_EMAIL", SMTP_USER or "no-reply@example.com")
TO_EMAILS = [e.strip() for e in os.getenv("TO_EMAILS", "").split(",") if e.strip()]
SMTP_USE_SSL = os.getenv("SMTP_USE_SSL", "false").lower() in ("1","true","yes")
SMTP_DEBUG = os.getenv("SMTP_DEBUG", "false").lower() in ("1","true","yes")

def _safe(s: str) -> str:
    return html.escape(s or "")

def build_digest_text(papers, summaries) -> str:
    lines = ["Daily arXiv AI Digest", ""]
    for i, p in enumerate(papers, 1):
        lines.append(f"{i}) {p.get('title','').strip()}")
        lines.append(f"Link: {p.get('link','')}")
        lines.append(summaries.get(p['id'], "[No summary]"))
        lines.append("")
    return "\n".join(lines)

def build_digest_html(papers, summaries) -> str:
    items = []
    for i, p in enumerate(papers, 1):
        items.append(f"""
          <div style="margin-bottom:18px;">
            <div style="font-weight:600;">{i}) {_safe(p.get('title','').strip())}</div>
            <div><a href="{_safe(p.get('link',''))}" target="_blank">Paper link</a></div>
            <pre style="white-space:pre-wrap;font:14px/1.4 system-ui, -apple-system, Segoe UI, Roboto, Arial;">
{_safe(summaries.get(p['id'], '[No summary]'))}
            </pre>
          </div>
        """)
    body = "\n".join(items)
    return f"""<html><body style="font-family:system-ui,-apple-system,Segoe UI,Roboto,Arial;margin:16px;">
      <h2 style="margin:0 0 10px 0;">Daily arXiv AI Digest</h2>{body}
      <hr><div style="color:#666;font-size:12px;">Generated by arxiv-digest</div>
    </body></html>"""

@retry(wait=wait_exponential(multiplier=1, min=2, max=8), stop=stop_after_attempt(3))
def send_email(subject: str, text_body: str, html_body: str):
    if not TO_EMAILS:
        raise RuntimeError("TO_EMAILS is empty. Set env var TO_EMAILS='you@example.com[,other@example.com]'")

    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = FROM_EMAIL
    msg["To"] = ", ".join(TO_EMAILS)
    msg.set_content(text_body)
    msg.add_alternative(html_body, subtype="html")

    logging.info(
        "Connecting SMTP %s:%s as %s (SSL=%s, DEBUG=%s) | From=%s | To=%s",
        SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_USE_SSL, SMTP_DEBUG, FROM_EMAIL, msg["To"]
    )

    try:
        if SMTP_USE_SSL:
            s = smtplib.SMTP_SSL(SMTP_HOST, SMTP_PORT, timeout=30, context=ssl.create_default_context())
        else:
            s = smtplib.SMTP(SMTP_HOST, SMTP_PORT, timeout=30)
        s.set_debuglevel(1 if SMTP_DEBUG else 0)
        s.ehlo()
        if not SMTP_USE_SSL:
            s.starttls()
            s.ehlo()
        s.login(SMTP_USER, SMTP_PASS)
        resp = s.send_message(msg)  # dict of failures; empty dict == success
        s.quit()
    except Exception as e:
        logging.error("SMTP send failed: %s", e)
        raise

    if resp:
        logging.warning("Partial send failures: %s", resp)
    else:
        logging.info("Email accepted by SMTP; subject=%s", subject)